name: Deploy React App

on:
  push:
    branches:
      - main  # Revisa si tu rama es 'main' o 'master'

# Añadimos esto para silenciar el aviso de Node 20 y usar la 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar código
        uses: actions/checkout@v4

      - name: 2. Instalar Node 24 y dependencias
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Actualizamos a la versión recomendada
          cache: 'npm'

      - name: 3. Construir aplicación (Build)
        run: |
          npm install
          npm run build

      - name: 4. Enviar a VPS mediante SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*"
          target: "/home/ubuntu/docker/projects/mi-app-react/"
          strip_components: 1
          overwrite: true # Forzamos que sobrescriba lo anterior